name: Test Github Action
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Github Action
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          paths: ${{ github.workspace }}/sample-content